# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)
variables:
  - group: external-variables
  - name: buildId
    value: '$(Build.BuildId)'
  - name: System.Debug
    value: true
  - template: variables.yml

stages :

- stage: Status
  displayName: ${{ variables.stageName }}
  jobs:
    - job:   
      displayName: ${{ variables.jobName }}
      variables:
        AUTH : "Authorization: Bearer $(System.AccessToken)"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: echo from variable template ${{ variables.scriptName }}
        - script: java -version && which java
        - script: curl -X GET -H '$(AUTH)' "$( echo "https://dev.azure.com/thierrychantier/$(System.TeamProject)/_apis/build/builds" | sed 's/ /%20/g' )" >> output.txt
        - script: cat output.txt
        - script: cat output.txt | jq -c '. .value[] | select(.sourceVersion | contains("$(Build.SourceVersion)")) | .id'

- stage: Build
  displayName: Build stage

  jobs:  
    - job:
      displayName: Job Test 2
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - template: parameters.yml
        parameters:
          containerName: 'test-az-cli'
      - bash: echo "Hello world " + $(Build.BuildId)

