# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)
variables:
  - group: external-variables
  - name: buildId
    value: '$(Build.BuildId)'
  - name: System.Debug
    value: true

stages :

- stage: Package
  displayName: Package web app

  jobs:
    - job: Package
      displayName: build and package backend
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Npm@1
          inputs:
            command: 'install' # Options: install, publish, custom
            workingDir: '$(System.DefaultWorkingDirectory)/fullwebapp/api'
            verbose: true
        - script: echo -e "ACCOUNT_NAME=$(secure-storage-account-name)\nACCOUNT_KEY=$(secure-storage-account-key)\nPORT=9000" > $(System.DefaultWorkingDirectory)/fullwebapp/.env
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fullwebapp/api'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).backend.zip
            replaceExistingArchive: true

        - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).backend.zip
          artifact: backend.webapp

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Package
  condition: succeeded('Package')
  jobs:
  - deployment: Deploy
    displayName: Deploy backend
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'no_approbation'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              inputs:
                azureSubscription: thierry-sandox
                appType: webAppLinux
                appName: test-webapp-semarchy
                runtimeStack: 'NODE|10.10'
                package: $(Pipeline.Workspace)/fullwebapp/$(Build.BuildId).backend.zip
                startUpCommand: "npm start"